# SPDX-License-Identifier: GPL-2.0
# gsensor drivers

obj-$(CONFIG_PS_AL3006) 		+= ps_al3006.o
obj-$(CONFIG_PS_STK3171) 		+= ps_stk3171.o
obj-$(CONFIG_PS_AP321XX) 		+= ps_ap321xx.o
obj-$(CONFIG_PS_STK3410) 		+= ps_stk3410.o
#david add 20210121
obj-$(CONFIG_PS_STK3X3X) 		+= ps_stk3x3x.o
obj-$(CONFIG_PS_STK3X8XX) 		+= ps_stk3x8xx.o
obj-$(CONFIG_PS_STK3A6X) 		+= ps_stk3a6x.o
